
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 18 23:50:26 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 15;
  public static final int INCREMENT = 23;
  public static final int CONST = 13;
  public static final int EQUALS = 26;
  public static final int NUMCONST = 46;
  public static final int CASE = 43;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int LESS = 30;
  public static final int MINUS = 19;
  public static final int DECREMENT = 24;
  public static final int RPAREN = 7;
  public static final int AND = 38;
  public static final int OR = 39;
  public static final int QMARK = 32;
  public static final int COMMA = 8;
  public static final int CLASS = 17;
  public static final int DIV = 21;
  public static final int LESS_EQUAL = 31;
  public static final int PLUS = 10;
  public static final int IF = 44;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int RBRACKET = 14;
  public static final int EQUAL = 11;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int MOD = 22;
  public static final int IDENT = 47;
  public static final int BREAK = 34;
  public static final int VOID = 12;
  public static final int SWITCH = 42;
  public static final int COLON = 33;
  public static final int ELSE = 45;
  public static final int LBRACE = 3;
  public static final int READ = 18;
  public static final int CHARCONST = 49;
  public static final int WHILE = 41;
  public static final int MORE_EQUAL = 29;
  public static final int NOT_EQUALS = 27;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int DO = 40;
  public static final int PRINT = 9;
  public static final int MORE = 28;
}

